# Generated by Django 5.0.3 on 2024-07-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
